import Head from 'next/head';
import Header from 'components/Header';
import Footer from 'components/Footer';
import Main from '/components/Main';
import Backgrounds from '@/components/Backgrounds';
// import Head from 'components/head';

// import { useAuth } from '@/contexts/auth';
// import {useState} from 'react';

// import LoginForm from 'components/LoginForm';

// import useResource from '../hooks/useResource';


export default function Home() {
  // const { user, login, logout } = useAuth();
  // const { resources } = useResource();

  
  return (
    <>
      <Head>
        <title>ThriveHQ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      
      

      {/* <Header user={user} logout={logout}/> */}
      {/* ternary uncommented to bypass login requirement,  */}
      {/* {user ?  */}
      <Backgrounds/>
      <div className='relative z10'>
      <Header className='relative z10'/>
      <Main/>
      </div>
      {/* :
      <LoginForm onLogin={login}/>
     
      } */}
      <Footer/>
    </>
  )
}
